const ultimateGuitarOutput2 = [
	'#c',
	'D G D',
	'Swing _low, sweet _chari_ot,',
	'A7',
	'Comin’ for to carry me _home.',
	'D7 G D',
	'Swing _low, sweet _chari_ot,',
	'A7 D',
	'Comin’ for to _carry me _home.',
	'',
	'D G D',
	'I _looked over Jordan, and _what did I _see,',
	'A7',
	'Comin’ for to carry me _home.',
	'D G D',
	'A _band of angels _comin’ after _me,',
	'A7 D',
	'Comin’ for to _carry me _home.',
	'',
	'#c',
	'',
	'',
];
export default ultimateGuitarOutput2;
