const editorModeOptions = {
	edit: [],
	play: [
		'chordsAndLyricsDisplay',
		'alignChordsWithLyrics',
		'harmonizeAccidentals',
		'preferredAccidentals',
		'useShortNamings',
		'simplifyChords',
		'transposeValue',

		'alignBars',
		'autoRepeatChords',
		'expandSectionMultiply',
		'columnsCount',
		'fontSize',
		'fontStyle',
		'chordsColor',
		'highlightChords',
	],
	print: [
		'chordsAndLyricsDisplay',
		'alignChordsWithLyrics',
		'harmonizeAccidentals',
		'preferredAccidentals',
		'useShortNamings',
		'simplifyChords',
		'transposeValue',

		'alignBars',
		'autoRepeatChords',
		'expandSectionMultiply',
		'documentSize',
		'documentMargins',
		'columnsCount',
		'columnBreakOnParagraph',
		'printFontSize',
		'fontStyle',
		'chordsColor',
		'highlightChords',
	],
	export: [
		'chordsAndLyricsDisplay',
		'alignChordsWithLyrics',
		'harmonizeAccidentals',
		'preferredAccidentals',
		'useShortNamings',
		'simplifyChords',
		'transposeValue',

		'style',
		'alignBars',
		'autoRepeatChords',
		'expandSectionMultiply',
	],
};

export default editorModeOptions;
