export default {
	songPreferences: {
		values: {
			chordsAndLyricsDisplay: 'all',
			alignChordsWithLyrics: true,
			harmonizeAccidentals: true,
			preferredAccidentals: 'auto',
			useShortNamings: true,
			simplifyChords: 'none',
			transposeValue: 0,
		},
		defaults: {
			chordsAndLyricsDisplay: 'all',
			alignChordsWithLyrics: true,
			harmonizeAccidentals: true,
			preferredAccidentals: 'auto',
			useShortNamings: true,
			simplifyChords: 'none',
			transposeValue: 0,
		},
		//userDefaults: {},
	},
	songFormatting: {
		values: {
			style: 'chordmark',
			alignBars: true,
			autoRepeatChords: true,
			expandSectionRepeats: true,
			documentSize: 'a4',
			documentMargins: 3,
			columnsCount: 1,
			columnBreakOnParagraph: true,
			fontSize: 0,
			printFontSize: 0,
			fontStyle: 'roboto',
			chordsColor: 'yellow',
			highlightChords: true,
		},
		defaults: {
			style: 'chordmark',
			alignBars: true,
			autoRepeatChords: true,
			expandSectionRepeats: true,
			documentSize: 'a4',
			documentMargins: 3,
			columnsCount: 1,
			columnBreakOnParagraph: true,
			fontSize: 0,
			printFontSize: 0,
			fontStyle: 'roboto',
			chordsColor: 'yellow',
			highlightChords: true,
		},
		//userDefaults: {},
	},
};
